### ISSUE TITLE
Неправильная формула для вычисления радиуса, перепроверь!

### ISSUE THREAD

**Issue by kryksyh** [MIET-ITS21-OOP-2017/domashnee-zadanie-no1-Daemon26#2]
https://github.com/MIET-ITS21-OOP-2017/domashnee-zadanie-no1-Daemon26/blob/0984c05a2984bafd214a335d116359b02b7f262f/Program.cs#L24

**Comment by Daemon26** [comment]
Внесены исправления.

**Comment by kryksyh** [comment]
Да, теперь все хорошо
